# Generated by Django 5.0.1 on 2024-01-31 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLunguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunguages', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('photo', models.ImageField(upload_to='')),
                ('role_description', models.CharField(max_length=300)),
                ('lunguages', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.programminglunguage')),
            ],
        ),
    ]
