# Generated by Django 5.0.1 on 2024-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_programminglunguage_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
