# Generated by Django 5.0.1 on 2024-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
